export const campaigns = [
  {
    id: "nic-icecreams-rashmika",
    title: "NIC & Rashmika",
    year: "2023",
    segment: "FMCG",
    creativeDirection: "Shark & Ink",
    category: "Brand Ambassadorship Program",
    heroImage: "/images/work-items/work-item-1.jpg",
    previewImage: "/images/work-items/work-item-1.jpg",
    challenge: "",
    solution: "",
    result: "",
    livePreview: "",
    description: "A high-recall celebrity brand collaboration between Rashmika and NIC Ice Creams, this campaign brings together one of India's most loved screen personalities with a premium dessert brand built around comfort, indulgence, and everyday joy. The collaboration uses Rashmika's warmth, relatability, and massive cross-market appeal to make NIC Ice Creams feel more personal, aspirational, and memorable.\n\nDesigned for strong digital reach, the campaign bridges cinema audiences, lifestyle consumers, food lovers, and social-first brand discovery. Each visual moment is crafted to create easy recall across Instagram, YouTube, short-form content, and brand-led media."
  },
  {
    id: "harley-davidson-raftaar",
    title: "Harley Davidson x Raftaar",
    year: "2026",
    segment: "Automotive",
    creativeDirection: "Shark & Ink",
    category: "Digital Brand Partnerships",
    heroImage: "/images/work-items/work-item-2.jpg",
    previewImage: "/images/work-items/work-item-2.jpg",
    challenge: "",
    solution: "",
    result: "",
    livePreview: "",
    description: "A powerful brand x artist collaboration between Raftaar and Harley, this campaign brings together hip-hop culture, motorcycle lifestyle, and high-performance attitude. Raftaar's strong youth connect and street credibility make him the perfect cultural bridge for a brand built around freedom, rebellion, and individuality.\n\nThe campaign is designed to travel beyond traditional advertising by tapping into music audiences, biking communities, lifestyle followers, and digital-first fans. With bold visuals, sharp styling, and high-energy storytelling, the collaboration creates strong social recall across reels, performance edits, launch content, and community-led conversations."
  },
  {
    id: "bajaj-pulsar-epr",
    title: "Bajaj Pulsar x EPR Iyer",
    year: "2025",
    segment: "Automotive",
    creativeDirection: "Shark & Ink",
    category: "Digital Brand Partnerships",
    heroImage: "/images/work-items/work-item-3.jpg",
    previewImage: "/images/work-items/work-item-3.jpg",
    challenge: "",
    solution: "",
    result: "",
    livePreview: "",
    description: "A high-impact brand x artist collaboration between Pulsar and EPR, this campaign brings together motorcycle performance and the raw voice of Indian hip-hop. EPR's powerful lyrical identity, street credibility, and youth connect make him a natural fit for a brand known for speed, edge, and self-expression.\n\nThe campaign is built to reach biking communities, hip-hop listeners, youth audiences, and digital-first consumers through bold visuals and performance-led storytelling. By combining rap, movement, and motorcycle culture, Pulsar strengthens its position as a brand for people who lead with attitude."
  },
  {
    id: "lotte-pepperos-yashraj",
    title: "Lotte (Pepero) x Yashraj Mukhate",
    year: "2025",
    segment: "FMCG",
    creativeDirection: "Shark & Ink",
    category: "Creator & Influencer Collaborations",
    heroImage: "/images/work-items/work-item-4.jpg",
    previewImage: "/images/work-items/work-item-4.jpg",
    challenge: "",
    solution: "",
    result: "",
    livePreview: "",
    description: "A creator-led brand collaboration for Pepero, this campaign brings together Yashraj Mukhate, Aditi Bhatia, Shantanu Maheshwari, and Taaruk Raina to create a highly shareable entertainment-first brand moment. Instead of relying on a conventional ad format, the campaign uses recognisable digital personalities to make the brand feel fun, current, and easy to engage with.\n\nEach collaborator adds a different audience layer, from music and internet culture to television, dance, lifestyle, and youth entertainment. This gives Pepero broader reach across fandoms, Instagram communities, YouTube audiences, and short-form content platforms."
  },
  {
    id: "jbl-dino-james",
    title: "JBL x Dino James",
    year: "2023",
    segment: "Electronics",
    creativeDirection: "Shark & Ink",
    category: "Digital Brand Partnerships",
    heroImage: "/images/work-items/work-item-5.jpg",
    previewImage: "/images/work-items/work-item-5.jpg",
    challenge: "",
    solution: "",
    result: "",
    livePreview: "",
    description: "A brand x artist collaboration between JBL and Dino James, this campaign leverages the intersection of audio technology and hip-hop culture. Dino James's authentic storytelling style and massive following among young Indian listeners make him an ideal voice for a brand built on premium sound quality and self-expression.\n\nThe campaign connects JBL with hip-hop audiences, content creators, and music enthusiasts through performance-driven visuals and digital-first storytelling that positions JBL as the sound of India's creative underground."
  },
  {
    id: "yung-raja-sting-f1",
    title: "Yung Raja x Sting x F1",
    year: "2024",
    segment: "FMCG",
    creativeDirection: "Shark & Ink",
    category: "Digital Brand Partnerships",
    heroImage: "/images/work-items/work-item-yung-raja.jpg",
    previewImage: "/images/work-items/work-item-yung-raja.jpg",
    challenge: "",
    solution: "",
    result: "",
    livePreview: "",
    description: "When PepsiCo’s Sting Energy partnered with Formula 1, strict contractual limitations blocked all trackside logos, broadcast branding, and on-car placements. Facing immediate visual invisibility against legacy competitors, creative agency Leo India engineered an auditory hijack titled \"The Unofficial Official Sound of F1.\" The strategy turned a massive restriction into a competitive advantage by exploiting the reality that a roaring F1 engine naturally mimics the vocalization of the word \"Stinggg.\" To globalize this audio-first concept, the agency deployed a multi-tier influencer architecture, combining global DJ Armin van Buuren with hyper-local icons like Singaporean-Tamil rapper Yung Raja, who blended the engine samples into his rapid-fire regional rap tracks. The impact was immediate and massive: the campaign generated hundreds of millions of digital views, bypassed traditional television advertising completely, and transformed a strict visual ban into a decentralized viral loop. By embedding the brand’s identity directly into the actual soundtrack of the sport, the agency successfully conditioned millions of young viewers across Southeast Asia and India to subconsciously recall the energy drink during every single race acceleration. This brilliant sonic positioning drove unprecedented youth engagement, cementing Sting's market dominance and commercial footprint across the entire APAC region."
  },
  {
    id: "lenskart-rashmeet-farhan",
    title: "Lenskart x Rashmeet Kaur & Farhan Khan",
    year: "2024",
    segment: "Fashion",
    creativeDirection: "Shark & Ink",
    category: "Creator & Influencer Collaborations",
    heroImage: "/images/work-items/work-item-7.jpg",
    previewImage: "/images/work-items/work-item-7.jpg",
    challenge: "Lenskart wanted to promote its hip-hop inspired eyewear collection through authentic cultural voices.",
    solution: "Managed creator coordination, production alignment, and campaign execution with Rashmeet Kaur and Farhan Khan, ensuring consistency in storytelling and visual identity.",
    result: "Delivered high engagement and reinforced Lenskart's youth-centric positioning.",
    livePreview: "Instagram Reel",
    description: ""
  },
  {
    id: "breakbounce-breakthebeat",
    title: "Breakbounce #BreakTheBeat",
    year: "2024",
    segment: "Fashion",
    creativeDirection: "Shark & Ink",
    category: "Creator & Influencer Collaborations",
    heroImage: "/images/work-items/work-item-8.jpg",
    previewImage: "/images/work-items/work-item-8.jpg",
    challenge: "Breakbounce needed cultural credibility within the hip-hop and streetwear ecosystem.",
    solution: "Conceptualized and executed the #BreakTheBeat campaign featuring The Spindoctor, D-Cypher, Archis Patil, Aman Shah, and Tiger Pop. Managed strategy, talent, production, and rollout.",
    result: "Generated strong organic buzz and positioned Breakbounce as a culture-first streetwear brand.",
    livePreview: "Instagram Reel",
    description: ""
  }
];
